//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EURISTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalog
    {
        public int Catalog_id { get; set; }
        public int Product_id { get; set; }
    }
}
